server:
  port: ${PORT:8082}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "optional:configserver:"

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from: ${SENDGRID_FROM}

gateway:
  url: ${GATEWAY_URL}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 día en milisegundos
logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
rabbitmq:
 addresses: ${RABBITMQ_URL}
 username: ${RABBITMQ_USER}
 password: ${RABBITMQ_PASS}
 virtual-host: ${RABBITMQ_VHOST}

management:
 endpoints:
  web:
   exposure:
    include: health,info,metrics,loggers
 endpoint:
  health:
   show-details: always