server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: moneyhousedigital.noreply@gmail.com
    password: vawrsgbgllzfxuxh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
        debug: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 día en milisegundos
logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework: INFO

rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
