spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: mySuperSecretKey123   # 👈 debe coincidir con jwt.secret en AuthService

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8085

main:
  allow-bean-definition-overriding: true
