spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      discovery:
        serviceId: config-server
      enabled: false 
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8087
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: http://localhost:8084
          predicates:
            - Path=/accounts/**
          filters:
            - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/digitalmoneyhouse
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
main:
  allow-bean-definition-overriding: true