spring:
  application:
    name: accounts-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: ${PORT:8084}


logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO
jwt:
  secret: ${JWT_SECRET}

internal:
  token: ${INTERNAL_TOKEN}

management:
  endpoints:
    web:
      exposure:
       include: health,info,metrics,env,loggers
  endpoint:
   health:
    show-details: always
    probes:
     enabled: true