spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://localhost:3306/account_service_db
    username: account_service_user
    password: nerea
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: "optional:configserver:"  # <--- Corrección aquí
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/digitalmoneyhouse
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8084
  servlet:
    context-path: /accounts

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework: INFO
jwt:
  secret: MysecretClabe23
